### ISSUE TITLE
There is a typo in the README

### ISSUE THREAD

**Issue by CloudsRL** [DanielSarmiento04/yolov10cpp#1]
"**The code use OpenCv 1.9.0_8**" is mentioned in the README file, but I found in the tasks file of .vscode that it should actually be **OpenCv4.9.0_8**. My guess is that when you were typing, 4 and 1 were close, so you made a typo.
Unfortunately, I am not proficient in using github, so I can only remind you in this way. Thank you very much for being able to implement yolov10 in C++ so quickly. This is of great significance to our graduate students.

**Comment by DanielSarmiento04** [comment]
Sure, Thank you for  your contribution and feedback, I will fix it, feel free to more comment
