### ISSUE TITLE
Boxes and predictions

### ISSUE THREAD

**Issue by victorsoyvictor** [DanielSarmiento04/yolov10cpp#2]
Hello, thanks for your quick cpp integration, unfortunately I don't get right boxes nor predictions:

`D:\BinaryFightFallDL60\Windows>yolov10_cpp.exe "D:\model_repository\yolov10n.onnx" "D:\workspace\ultralytics\ultralytics\assets\bus.jpg"
Class ID: bottle Confidence: 0.916529 BBox: [-249848, -90171, 514108, 477502]
Class ID: tv Confidence: 26 BBox: [111294, 258447, 340157, 32]
Class ID: tennis racket Confidence: 0.654325 BBox: [217475, 478429, 8, 28080]
Class ID: keyboard Confidence: 282.15 BBox: [232214, -122489, 0, 244992]
Class ID: pizza Confidence: 50.4356 BBox: [-57, -178962, 122, 357925]
Class ID: potted plant Confidence: 286.351 BBox: [-99585, 2685, 199170, 53383]
Class ID: handbag Confidence: 27 BBox: [107604, 125818, 238919, 2]
Class ID: hair drier Confidence: 370.461 BBox: [279138, -96112, 19440, 192228]
Class ID: remote Confidence: 9.58556 BBox: [-25, -144016, 52, 354992]
Class ID: hot dog Confidence: 410.912 BBox: [-138563, -9662, 281986, 19330]
Class ID: refrigerator Confidence: 288.261 BBox: [324737, -100243, 810, 200489]
Class ID: giraffe Confidence: 25.2895 BBox: [-521, -74274, 1044, 232789]
Class ID: banana Confidence: 451.191 BBox: [-55867, -33059, 170054, 66878]
Class ID: chair Confidence: 5 BBox: [35778, 9318, 280054, 0]
Class ID: knife Confidence: 200.953 BBox: [99481, 502617, 0, 42120]`

![image](https://github.com/DanielSarmiento04/yolov10cpp/assets/10844623/56ae70f0-5d82-43f7-b629-3cf937d66412)

I have built your code and export a couple of onnx models using the script (size x and n).

**Comment by DanielSarmiento04** [comment]
Sure, Can you provide the follow information to analyze and replicate the result 


OS => Windows, Mac, linux

Version dependency => Example onnx runtime 1.7.1, OpenCv version 1.8.1 and ffmpeg version.

Yolo version Use

**Comment by victorsoyvictor** [comment]
Hello, 

OS=> Windows
Onnx => 1.17. OpenCV => 4.7 (built with CUDA and ffmpeg)

Ultralytics YOLOv8.1.34 🚀 Python-3.10.6 torch-2.3.0+cu118 CUDA:0 (NVIDIA GeForce RTX 3050 Laptop GPU, 4096MiB)

Thanks for your help.

**Comment by SunEve** [comment]
Me too

OS=> Windows CUDA11.6
onnxruntime-win-x64-gpu-1.18.0
opencv-4.9.0-windows for VS2019

Use yolov10x.onnx IMG_4057.JPG

Class ID: 57 Confidence: 0.962906 BBox: [489222, -32094, 2578670, 1931335]
Class ID: 2 Confidence: 63 BBox: [-179409, 224386, 814113, 26]
Class ID: 13 Confidence: 632.656 BBox: [299195, 500209, 8, 220752]
Class ID: 42 Confidence: 74.5786 BBox: [1201914, -172579, 165312, 345166]
Class ID: 77 Confidence: 639.761 BBox: [-1277266, -251175, 2554539, 895470]
Class ID: 46 Confidence: 259.634 BBox: [-199687, -32552, 923534, 66012]
Class ID: 56 Confidence: 55 BBox: [-144297, 168111, 724507, 1]
Class ID: 12 Confidence: 230.137 BBox: [1194797, -958009, 318528, 1916020]
Class ID: 47 Confidence: 508.602 BBox: [-495975, 186741, 991952, 1493]
Class ID: 64 Confidence: 280.263 BBox: [-167138, -34842, 922949, 70283]
Class ID: 68 Confidence: 65 BBox: [281076, 241948, 1462843, 0]
Class ID: 12 Confidence: 230.137 BBox: [1247285, -958010, 266112, 1916020]
Class ID: 17 Confidence: 508.602 BBox: [-495975, 123237, 991952, 1493]
Class ID: 4 Confidence: 268.328 BBox: [-296326, 152532, 1036173, 440476]
Class ID: 2 Confidence: 55 BBox: [234063, 1934699, 1376598, 0]

**Comment by SunEve** [comment]
> Me too
> 
> OS=> Windows CUDA11.6 onnxruntime-win-x64-gpu-1.18.0 opencv-4.9.0-windows for VS2019
> 
> Use yolov10x.onnx IMG_4057.JPG
> 
> Class ID: 57 Confidence: 0.962906 BBox: [489222, -32094, 2578670, 1931335] Class ID: 2 Confidence: 63 BBox: [-179409, 224386, 814113, 26] Class ID: 13 Confidence: 632.656 BBox: [299195, 500209, 8, 220752] Class ID: 42 Confidence: 74.5786 BBox: [1201914, -172579, 165312, 345166] Class ID: 77 Confidence: 639.761 BBox: [-1277266, -251175, 2554539, 895470] Class ID: 46 Confidence: 259.634 BBox: [-199687, -32552, 923534, 66012] Class ID: 56 Confidence: 55 BBox: [-144297, 168111, 724507, 1] Class ID: 12 Confidence: 230.137 BBox: [1194797, -958009, 318528, 1916020] Class ID: 47 Confidence: 508.602 BBox: [-495975, 186741, 991952, 1493] Class ID: 64 Confidence: 280.263 BBox: [-167138, -34842, 922949, 70283] Class ID: 68 Confidence: 65 BBox: [281076, 241948, 1462843, 0] Class ID: 12 Confidence: 230.137 BBox: [1247285, -958010, 266112, 1916020] Class ID: 17 Confidence: 508.602 BBox: [-495975, 123237, 991952, 1493] Class ID: 4 Confidence: 268.328 BBox: [-296326, 152532, 1036173, 440476] Class ID: 2 Confidence: 55 BBox: [234063, 1934699, 1376598, 0]

Change the function filterDetections to this to get the correct result.
std::vector<Detection> filterDetections(const std::vector<float> &results, float confidence_threshold, int img_width, int img_height)
{
    std::vector<Detection> detections;
    const int num_detections = results.size() / 6;
    for (int i = 0; i < num_detections; ++i)
    {
        float left = results[i * 6 + 0];
        float top = results[i * 6 + 1];
        float width = results[i * 6 + 2] - left;
        float height = results[i * 6 + 3] - top;
        float confidence = results[i * 6 + 4];
        int class_id = results[i * 6 + 5];

        if (confidence >= confidence_threshold /*&& class_id != -1*/)
        {
            detections.push_back({confidence, cv::Rect(static_cast<int>(left), static_cast<int>(top), static_cast<int>(width), static_cast<int>(height)), class_id});
        }
    }

    return detections;
}

To restore the size, use：
for (const auto& detection : detections)
		{
			float widthscale = input_shape[2] / (float)img_width;
            float heightscale = input_shape[3] / (float)img_height;

			std::cout << "Class NAME: " << CLASS_NAMES[detection.class_id] << " Confidence: " << detection.confidence
				<< " BBox: [" << detection.bbox.x / widthscale << ", " << detection.bbox.y / heightscale << ", "
				<< detection.bbox.width / widthscale << ", " << detection.bbox.height / heightscale << "]" << std::endl;

			cv::rectangle(image, cv::Rect(detection.bbox.x/ widthscale, detection.bbox.y/ heightscale, detection.bbox.width/ widthscale, detection.bbox.height/ heightscale), cv::Scalar(detection.class_id + 10, 255, 0), 1);
		}

![out](https://github.com/DanielSarmiento04/yolov10cpp/assets/19798572/a773733d-9109-46b2-94b8-bd47b02866af)

**Comment by DanielSarmiento04** [comment]
> > Me too
> > OS=> Windows CUDA11.6 onnxruntime-win-x64-gpu-1.18.0 opencv-4.9.0-windows for VS2019
> > Use yolov10x.onnx IMG_4057.JPG
> > Class ID: 57 Confidence: 0.962906 BBox: [489222, -32094, 2578670, 1931335] Class ID: 2 Confidence: 63 BBox: [-179409, 224386, 814113, 26] Class ID: 13 Confidence: 632.656 BBox: [299195, 500209, 8, 220752] Class ID: 42 Confidence: 74.5786 BBox: [1201914, -172579, 165312, 345166] Class ID: 77 Confidence: 639.761 BBox: [-1277266, -251175, 2554539, 895470] Class ID: 46 Confidence: 259.634 BBox: [-199687, -32552, 923534, 66012] Class ID: 56 Confidence: 55 BBox: [-144297, 168111, 724507, 1] Class ID: 12 Confidence: 230.137 BBox: [1194797, -958009, 318528, 1916020] Class ID: 47 Confidence: 508.602 BBox: [-495975, 186741, 991952, 1493] Class ID: 64 Confidence: 280.263 BBox: [-167138, -34842, 922949, 70283] Class ID: 68 Confidence: 65 BBox: [281076, 241948, 1462843, 0] Class ID: 12 Confidence: 230.137 BBox: [1247285, -958010, 266112, 1916020] Class ID: 17 Confidence: 508.602 BBox: [-495975, 123237, 991952, 1493] Class ID: 4 Confidence: 268.328 BBox: [-296326, 152532, 1036173, 440476] Class ID: 2 Confidence: 55 BBox: [234063, 1934699, 1376598, 0]
> 
> Change the function filterDetections to this to get the correct result. std::vector filterDetections(const std::vector &results, float confidence_threshold, int img_width, int img_height) { std::vector detections; const int num_detections = results.size() / 6; for (int i = 0; i < num_detections; ++i) { float left = results[i * 6 + 0]; float top = results[i * 6 + 1]; float width = results[i * 6 + 2] - left; float height = results[i * 6 + 3] - top; float confidence = results[i * 6 + 4]; int class_id = results[i * 6 + 5];
> 
> ```
>     if (confidence >= confidence_threshold /*&& class_id != -1*/)
>     {
>         detections.push_back({confidence, cv::Rect(static_cast<int>(left), static_cast<int>(top), static_cast<int>(width), static_cast<int>(height)), class_id});
>     }
> }
> 
> return detections;
> ```
> 
> }
> 
> To restore the size, use： for (const auto& detection : detections) { float widthscale = input_shape[2] / (float)img_width; float heightscale = input_shape[3] / (float)img_height;
> 
> ```
> 		std::cout << "Class NAME: " << CLASS_NAMES[detection.class_id] << " Confidence: " << detection.confidence
> 			<< " BBox: [" << detection.bbox.x / widthscale << ", " << detection.bbox.y / heightscale << ", "
> 			<< detection.bbox.width / widthscale << ", " << detection.bbox.height / heightscale << "]" << std::endl;
> 
> 		cv::rectangle(image, cv::Rect(detection.bbox.x/ widthscale, detection.bbox.y/ heightscale, detection.bbox.width/ widthscale, detection.bbox.height/ heightscale), cv::Scalar(detection.class_id + 10, 255, 0), 1);
> 	}
> ```
> 
> ![out](https://private-user-images.githubusercontent.com/19798572/334636881-a773733d-9109-46b2-94b8-bd47b02866af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NTM1NTQsIm5iZiI6MTcxNjk1MzI1NCwicGF0aCI6Ii8xOTc5ODU3Mi8zMzQ2MzY4ODEtYTc3MzczM2QtOTEwOS00NmIyLTk0YjgtYmQ0N2IwMjg2NmFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI5VDAzMjczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3ZTkxZDllZWJiNjQxNTRlNGFmODg5NmU5ZGM2ZjYxZGQ5Yjc4NjlmYTg1YjM4MTViOGEwMWE1M2NmNjQ0ZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.oBQbAeg_qRCnFUyFwpvIn2kekwT-GVV5g3ktjOCvv1M)

thanks for your approach, yeah the index iterator was a mistake over the result
