### ISSUE TITLE
Confidence level exception

### ISSUE THREAD

**Issue by xufabs** [DanielSarmiento04/yolov10cpp#4]
First of all thank you for your contribution.

But there was a problem.

There are some pictures using this program for ONNXRUNTIME C++ inference, the confidence performance is too different from the yolov10 official inference.

The woman in white has only 0.5 confidence, while python has 0.8.

I've also used some other people's images, which have a 0.8 confidence with python, but only 0.1 with this project, and will even be recognized as birds.

I want to know what caused this.

onnxruntime-linux-x64-1.17.1

![1](https://github.com/DanielSarmiento04/yolov10cpp/assets/77445897/b2cd6e58-8695-415b-9c90-613fccf79a4b)

![result](https://github.com/DanielSarmiento04/yolov10cpp/assets/77445897/3b1c793b-e43f-413d-9131-edf7f526abc9)
yolov10cpp + yolov10n.onnx 👆

![1](https://github.com/DanielSarmiento04/yolov10cpp/assets/77445897/d5d70630-9fde-4688-93a2-1ca53cd1c04d)
yolov10py + yolov10n.pt 👆

**Comment by xufabs** [comment]
> First of all thank you for your contribution.
> 
> But there was a problem.
> 
> There are some pictures using this program for ONNXRUNTIME C++ inference, the confidence performance is too different from the yolov10 official inference.
> 
> The woman in white has only 0.5 confidence, while python has 0.8.
> 
> I've also used some other people's images, which have a 0.8 confidence with python, but only 0.1 with this project, and will even be recognized as birds.
> 
> I want to know what caused this.
> 
> onnxruntime-linux-x64-1.17.1
> 
> ![1](https://private-user-images.githubusercontent.com/77445897/344843363-b2cd6e58-8695-415b-9c90-613fccf79a4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODQ3OTIsIm5iZiI6MTcxOTg4NDQ5MiwicGF0aCI6Ii83NzQ0NTg5Ny8zNDQ4NDMzNjMtYjJjZDZlNTgtODY5NS00MTViLTljOTAtNjEzZmNjZjc5YTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxNDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYmI2Yjg3ZDAxZTJkZDc0NDA2MTFmNDk3ZTE4ZDdkYTk3MDhmMzZlNGNjM2QxZWRhZjg1NDlmODE2MzE5YjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.W2wOL-v9D4exyAEi5YkAtFl02hpAQBhe1KilYIKVfFY)
> 
> ![result](https://private-user-images.githubusercontent.com/77445897/344843559-3b1c793b-e43f-413d-9131-edf7f526abc9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODQ3OTIsIm5iZiI6MTcxOTg4NDQ5MiwicGF0aCI6Ii83NzQ0NTg5Ny8zNDQ4NDM1NTktM2IxYzc5M2ItZTQzZi00MTNkLTkxMzEtZWRmN2Y1MjZhYmM5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxNDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk4NjVhODdhNzA3MWEzNGZhNzQzMDk5ZTA4YzE0MzMxMzkyYzExMjRkMzI4NWYyYTI2YzA3YjA1OTE0YTUxZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wynwmjXHZc2qe-RsyY8TDtKIaI-f4V1_doPiImjjZaQ) yolov10cpp + yolov10n.onnx 👆
> 
> ![1](https://private-user-images.githubusercontent.com/77445897/344843723-d5d70630-9fde-4688-93a2-1ca53cd1c04d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4ODQ3OTIsIm5iZiI6MTcxOTg4NDQ5MiwicGF0aCI6Ii83NzQ0NTg5Ny8zNDQ4NDM3MjMtZDVkNzA2MzAtOWZkZS00Njg4LTkzYTItMWNhNTNjZDFjMDRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAxNDEzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlNmQzYTgxMzE4NGM1OWM1MGNjMTA1Yjc2YjY3OGEwOTgwM2NhMzI1Yzc4NzE3N2VmYzIzYTJlZDcxNWJkNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BzPhwjYdueTntZtc9AUapvJy--Gv3NXc1AAFSaXbXWc) yolov10py + yolov10n.pt 👆

ubuntu 24.04
opencv 4.5.3

**Comment by xufabs** [comment]
https://github.com/UNeedCryDear/yolov8-opencv-onnxruntime-cpp
I hope this can help you to debug 


![图片](https://github.com/DanielSarmiento04/yolov10cpp/assets/77445897/17bd48ee-acef-44f9-9786-d20fccb13343)
yolov8 onnxruntime cpu cpp  + yolov8n.onnx

**Comment by DanielSarmiento04** [comment]
Sure, I replicate this result, and yeah, there is a different between the both

**Comment by sdreamforchen** [comment]
> Sure, I replicate this result, and yeah, there is a different between the both

Can you directly supply ONNX model of yolov10 for downloading in your github page?

**Comment by xufabs** [comment]
https://github.com/Ultraopxt/yolov10cpp 

maybe this can help 

> > Sure, I replicate this result, and yeah, there is a different between the both
> 
> Can you directly supply ONNX model of yolov10 for downloading in your github page?



> Sure, I replicate this result, and yeah, there is a different between the both

**Comment by DanielSarmiento04** [comment]
I've some experiment with change a lot parameters and the best way at this moment I recommend you that lower the threshold confidences 
![result](https://github.com/user-attachments/assets/a5338d84-ac4a-4388-b2eb-081f1ab8a43a)

**Comment by DanielSarmiento04** [comment]
> [https://github.com/Ultraopxt/yolov10cpp，maybe](https://github.com/Ultraopxt/yolov10cpp%EF%BC%8Cmaybe) this can help
> 
> > > Sure, I replicate this result, and yeah, there is a different between the both
> > 
> > 
> > Can you directly supply ONNX model of yolov10 for downloading in your github page?
> 
> > Sure, I replicate this result, and yeah, there is a different between the botbut I think that is no necessary apply a letter box to ma

It's a good idea

**Comment by DanielSarmiento04** [comment]
![result](https://github.com/user-attachments/assets/82391d6e-d827-42e7-82ab-9a8f3f122a02)


With letter box implentations
